
workflows:
  android-xml-workflow:
    name: Android XML Build Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - android_credentials
      vars:
        JAVA_VERSION: "17"
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Build Android APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/**/*.apk
